kubernetes:
  pod_config:
    spec:
      containers:
        - env:
          - name: MY_ENV_VAR
            value: MY_ENV_VALUE
          volumeMounts:       # Custom volume mounts for the pod
            - mountPath: /foo
              name: example-volume
      volumes:
        - name: example-volume
          hostPath:
            path: /tmp
            type: Directory