apiVersion: apps/v1
kind: Deployment
metadata:
  name: cogvlm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cogvlm
  template:
    metadata:
      labels:
        app: cogvlm
    spec:
      containers:
      - name: cogvlm
        image: public.ecr.aws/d6u1k1m2/cogvlmquant:latest
        resources:
          requests:
            memory: "20Gi"
          limits:
            memory: "25Gi"