apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cogvlm-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cogvlm-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # For memory-based autoscaling, use custom metrics (not shown here)